PPZ:
  low: "Ты не стремишься выглядеть в глазах окружающих лучше, чем есть на самом деле."
  mid: "Ты в меру критичен по отношению к себе, у тебя много знакомых и друзей, но это не мешает тебе иметь собственную точку зрения и следовать своим убеждениям."
  high: "Тебе важно соответствовать ожиданиям окружающих, чтобы другие хорошо относились к тебе и давали защиту."

PVG:
  low: "Ты не стремишься общаться с большим кругом лиц, проявляется независимость, желание оставаться в стороне от группы и её жизни."
  mid: "Ты активно взаимодействуешь в группе, участвуешь в её жизни и получаешь поддержку со стороны других участников."
  high: "Ты чувствуешь себя дискомфортно, если находишься без компании. Тебе нравится находиться в кругу друзей, делать сообща то, что они предложили. Чаще всего ты согласен с мнением друзей и их решениями."

PAU:
  low: "Ты стремишься не нарушать правила, нормы поведения и договорённости. Тебя очень раздражают и огорчают ситуации, когда это приходится делать."
  mid: "Ты критичен по отношению к своему поведению и считаешь для себя недопустимым совершение социально порицаемых поступков, хотя понимаешь, что бывают ситуации-исключения."
  high: "Ты не боишься нарушать нормы и правила, поскольку понимаешь, что существуют двойные стандарты в оценке поведения и есть разделение людей на тех, «кому можно всё», и тех, «кому ничего нельзя». Тем не менее ты не всегда можешь рассчитать последствия своего поведения."

SR:
  low: "Ты предусмотрителен и осторожен, не готов пойти на риск ради достижения цели, решения задач, получения нужного результата. Ситуации неопределённости напрягают тебя."
  mid: "Ты готов попробовать что-то новое, можешь действовать в ситуации неопределённости ради достижения цели, решения задачи, получения нужного результата, но только если понимаешь, что риск неудачи меньше, чем вероятность достижения успеха."
  high: "Тебе нравится «щекотать нервы», переживать удовольствие от риска и драйва."

IM:
  low: "Ты осторожен, рационален и легко контролируешь свои эмоции."
  mid: "Ты естественно и адекватно проявляешь свои эмоции, но при необходимости можешь контролировать и сдерживать их."
  high: "Для тебя характерны непосредственность, эмоциональность, открытость. Ты легко «загораешься» новыми идеями, откликаешься на новые предложения."


TR:
  low: "Ты достаточно прагматичен и тебя мало что тревожит. Для тебя важно оценивать других людей, знания, ситуации с позиции выгоды для себя."
  mid: "Ты не тревожишься по пустякам, рационально и спокойно относишься к сложным и неудачам."
  high: "Ты склонен чрезмерно тревожиться и переживать из-за разных ситуаций, застенчив и не любишь общаться с малознакомыми людьми. Для тебя важны поддержка и одобрение твоих близких и друзей."


FR:
  low: "Ты ставишь перед собой достижимые цели и не боишься препятствий для их реализации. При возникновении трудностей ты сохраняешь спокойствие, не нервничаешь и показываешь высокую терпеливость в преодолении затруднений."
  mid: "При возникновении трудностей в достижении цели ты ищешь возможные выходы из сложной ситуации, хотя иногда начинаешь переживать из-за того, что всё складывается не просто."
  high: "Ты испытываешь высокое напряжение и разочарование, если возникают даже незначительные трудности в достижении важной для тебя цели."


DE:
  low: "Нарушение принятых в обществе правил поведения ты считаешь для себя невозможным и недопустимым."
  mid: "Ты обладаешь хорошей адаптивностью и пластичностью поведения. Соблюдение норм и правил для тебя сочетается с возможностью их нарушения в зависимости от требований реальности и ситуации, особенно если это нарушение не несёт в себе явного вреда для окружающих."
  high: "Ты не стремишься соблюдать правила, предписанные обществом, что может приводить к неблагоприятным последствиям и наказаниям."


PR:
  low: "В твоих отношениях с родителями возможны конфликты, ты чувствуешь недостаток внимания с их стороны."
  mid: "Твои отношения с родителями зависят от ситуации. Ты делишься с ними положительными событиями и, вероятно, умалчиваешь о том, что им будет неприятно услышать."
  high: "Твои отношения с родителями отличаются эмоциональной близостью, взаимным доверием и поддержкой."


PO:
  low: "В классе (группе) ты избирательно поддерживаешь отношения только с несколькими людьми."
  mid: "В классе (группе) ты пользуешься авторитетом у отдельных людей или группы, с ними поддерживаешь дружеские отношения."
  high: "В классе (группе) ты пользуешься авторитетом у большинства одноклассников (одногруппников) и легко поддерживаешь со всеми дружеские отношения."


SA:
  low: "Ты достаточно сдержан в установлении и поддержании социальных контактов, предпочитаешь уединение."
  mid: "Ты устанавливаешь и поддерживаешь социальные контакты в соответствии со своими интересами или для решения конкретных задач."
  high: "Ты проявляешь инициативу в социальном взаимодействии и занимаешь активную жизненную позицию."


SP:
  low: "Тебе сложно контролировать своё поведение, многие решения ты принимаешь ситуативно, под влиянием эмоций."
  mid: "Ты стараешься контролировать своё поведение, но при переживании сильных эмоций можешь быть несдержанным."
  high: "Ты всегда контролируешь своё поведение, сдержан и рассудителен."


SZ:
  low: "Ты предпочитаешь выполнять простые задачи, с которыми точно сможешь справиться."
  mid: "Ты способен справиться со сложными задачами, но при столкновении с трудностями и неудачами можешь отказаться от дальнейшего выполнения деятельности."
  high: "Ты справляешься со сложными задачами, отличаешься целеустремлённостью и доводишь начатое дело до конца."


AN:
  low: "Тебе сложно соблюдать правила и нормы поведения."
  mid: "Ты способен соблюдать правила и нормы поведения, но можешь нарушить их, если это не причиняет вреда окружающим."
  high: "Ты всегда стремишься к соблюдению норм и правил."


FU:
  low: "Тебе сложно принимать решения и действовать в ситуации неопределённости."
  mid: "Ты способен принимать решения и действовать в кратковременных ситуациях неопределённости."
  high: "Ты способен принимать решения и эффективно действовать в ситуациях неопределённости."

DO:
  low: "Ты сдержан в общении с другими людьми, предпочитаешь не делиться своими эмоциями с окружающими."
  mid: "Ты коммуникабелен, общителен и способен конструктивно отстаивать свою точку зрения."
  high: "Ты дружелюбен, открыт в общении с другими людьми и стараешься избегать конфликтов."