# шкалы кодируем латиницей, чтобы удобно было в коде
# risk_scales и protect_scales помогут суммировать блоки
risk_scales: [PPZ, PVG, PAU, SR, IM, TR]
protect_scales: [PR, PO, SA, SP, FU, AN]
lie_scale: LZ

# mapping шкала -> номера пунктов (строго 7 на шкалу)
keys:
  PPZ: [1, 14, 27, 40, 53, 66, 79, 0]   # пример; поставь реальные 7 номеров
  PVG: [2, 15, 28, 41, 54, 67, 80, 0]
  PAU: [3,16, 29, 42, 55, 68, 81, 0]
  SR:  [4,17, 30, 43, 56, 69, 82, 0]
  IM:  [5,18, 31, 44, 57, 70, 83, 0]
  TR:  [6,19, 32, 45, 58, 71, 84, 0]
  PR:  [7,20, 33, 46, 59, 72, 85, 0]
  PO:  [8,21, 34, 47, 60, 73, 86, 0]
  SA:  [9,22, 35, 48, 61, 74, 87, 0]
  SP:  [10,23, 36, 49, 62, 75, 88, 0]
  FU:  [11,24, 37, 50, 63, 76, 89, 0]
  AN:  [12,25, 38, 51, 64, 77, 90, 0]
  LZ:  [13,26, 39, 52, 65, 78, 91, 0]
