A:
  hearing:
    female:
      irp:
        низкий: [1, 26]
        средний: [27, 30]
        высокий: [31, 100]
      kveripo:
        низкий: [0.00, 0.43]
        высокий: [0.43, 1.00]
    male:
      irp:
        низкий: [1, 26]
        средний: [27, 30]
        высокий: [31, 100]
      kveripo:
        низкий: [0.00, 0.43]
        высокий: [0.43, 1.00]

  vision:
    female:
      irp:
        низкий: [1, 38]
        средний: [39, 44]
        высокий: [45, 100]
      kveripo:
        низкий: [0.00, 0.84]
        высокий: [0.84, 1.00]
    male:
      irp:
        низкий: [1, 37]
        средний: [38, 41]
        высокий: [42, 100]
      kveripo:
        низкий: [0.00, 0.80]
        высокий: [0.80, 1.00]

  motor:
    female:
      irp:
        низкий: [1, 38]
        средний: [39, 45]
        высокий: [46, 100]
      kveripo:
        низкий: [0.00, 0.45]
        высокий: [0.45, 1.00]
    male:
      irp:
        низкий: [1, 34]
        средний: [35, 40]
        высокий: [41, 100]
      kveripo:
        низкий: [0.00, 0.40]
        высокий: [0.40, 1.00]


B:
  hearing:
    female:
      irp:
        низкий: [1, 27]
        средний: [28, 31]
        высокий: [32, 100]
      kveripo:
        низкий: [0.00, 0.47]
        высокий: [0.47, 1.00]
    male:
      irp:
        низкий: [1, 27]
        средний: [28, 31]
        высокий: [32, 100]
      kveripo:
        низкий: [0.00, 0.47]
        высокий: [0.47, 1.00]

  vision:
    female:
      irp:
        низкий: [1, 27]
        средний: [28, 31]
        высокий: [32, 100]
      kveripo:
        низкий: [0.00, 0.47]
        высокий: [0.47, 1.00]
    male:
      irp:
        низкий: [1, 27]
        средний: [28, 31]
        высокий: [32, 100]
      kveripo:
        низкий: [0.00, 0.47]
        высокий: [0.47, 1.00]

  motor:
    female:
      irp:
        низкий: [1, 29]
        средний: [30, 34]
        высокий: [35, 100]
      kveripo:
        низкий: [0.00, 0.57]
        высокий: [0.57, 1.00]
    male:
      irp:
        низкий: [1, 29]
        средний: [30, 34]
        высокий: [35, 100]
      kveripo:
        низкий: [0.00, 0.57]
        высокий: [0.57, 1.00]


C:
  hearing:
    female:
      irp:
        низкий: [1, 31]
        средний: [32, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.57]
        высокий: [0.57, 1.00]
    male:
      irp:
        низкий: [1, 31]
        средний: [32, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.57]
        высокий: [0.57, 1.00]

  vision:
    female:
      irp:
        низкий: [1, 31]
        средний: [32, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.60]
        высокий: [0.60, 1.00]
    male:
      irp:
        низкий: [1, 31]
        средний: [32, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.60]
        высокий: [0.60, 1.00]

  motor:
    female:
      irp:
        низкий: [1, 32]
        средний: [33, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.60]
        высокий: [0.60, 1.00]
    male:
      irp:
        низкий: [1, 32]
        средний: [33, 36]
        высокий: [37, 100]
      kveripo:
        низкий: [0.00, 0.60]
        высокий: [0.60, 1.00]
