A:
  hearing:
    female:
      IRP_bands:   { norm: [1,26], over: [27,30], high: [31,100] }
      KVERIPO_max: 0.43
    male:
      IRP_bands:   { norm: [1,26], over: [27,30], high: [31,100] }
      KVERIPO_max: 0.43

  vision:
    female:
      IRP_bands:   { norm: [1,38], over: [39,45], high: [46,100] }
      KVERIPO_max: 0.84
    male:
      IRP_bands:   { norm: [1,37], over: [38,41], high: [42,100] }
      KVERIPO_max: 0.80

  motor:
    female:
      IRP_bands:   { norm: [1,38], over: [39,45], high: [46,100] }
      KVERIPO_max: 0.45
    male:
      IRP_bands:   { norm: [1,34], over: [35,40], high: [41,100] }
      KVERIPO_max: 0.40

B:
  hearing:
    female:
      IRP_bands:   { norm: [1,27], over: [28,31], high: [32,100] }
      KVERIPO_max: 0.47
    male:
      IRP_bands:   { norm: [1,27], over: [28,31], high: [32,100] }
      KVERIPO_max: 0.47

  vision:
    female:
      IRP_bands:   { norm: [1,27], over: [28,31], high: [32,100] }
      KVERIPO_max: 0.47
    male:
      IRP_bands:   { norm: [1,27], over: [28,31], high: [32,100] }
      KVERIPO_max: 0.47

  motor:
    female:
      IRP_bands:   { norm: [1,29], over: [30,34], high: [35,100] }
      KVERIPO_max: 0.57
    male:
      IRP_bands:   { norm: [1,29], over: [30,34], high: [35,100] }
      KVERIPO_max: 0.57

C:
  hearing:
    female:
      IRP_bands:   { norm: [1,31], over: [32,36], high: [37,100] }
      KVERIPO_max: 0.57
    male:
      IRP_bands:   { norm: [1,31], over: [32,36], high: [37,100] }
      KVERIPO_max: 0.57

  vision:
    female:
      IRP_bands:   { norm: [1,31], over: [32,36], high: [37,100] }
      KVERIPO_max: 0.60
    male:
      IRP_bands:   { norm: [1,31], over: [32,36], high: [37,100] }
      KVERIPO_max: 0.60

  motor:
    female:
      IRP_bands:   { norm: [1,32], over: [33,36], high: [37,100] }
      KVERIPO_max: 0.60
    male:
      IRP_bands:   { norm: [1,32], over: [33,36], high: [37,100] }
      KVERIPO_max: 0.60
